/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selfservicestation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author PC
 */
public class KreditnaKartica_placanje extends javax.swing.JFrame {

    /**
     * Creates new form KreditnaKartica_placanje
     */
    public KreditnaKartica_placanje() {
        initComponents();
    }

     
    
    
    int creditCardID1 = 1;
    int creditCardPin1 = 1111;
    double creditCardBalance1 = 100.1;
    
    
    int creditCardID2 = 2;
    int creditCardPin2 = 2222;
    double creditCardBalance2 = 200.2;
    
    
    int creditCardID3 = 3;
    int creditCardPin3 = 3333;
    double creditCardBalance3 = 300.3;

   
   

    public KreditnaKartica_placanje (String KojeGorivo, String KolicinaNovca, String KolicinaGorivaPopust){
        initComponents();
      
        izabranoGorivo_kk.setText(KojeGorivo);
        KreditnaKarticaKolicinaNovca.setText(KolicinaNovca);
        kolicinaGoriva_kk.setText(KolicinaGorivaPopust);
         
    }
    
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kreditnaKarticaID = new javax.swing.JTextField();
        kreditnaKarticaPIN = new javax.swing.JTextField();
        KreditnaKarticaKolicinaNovca = new javax.swing.JLabel();
        button_potvrdiUplatu_KK = new javax.swing.JButton();
        button_nazad_KK = new javax.swing.JButton();
        izabranoGorivo_kk = new javax.swing.JLabel();
        kolicinaGoriva_kk = new javax.swing.JLabel();
        ukupnoUplaceno_kk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("selected payment type - credit card");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("credit card ID :");

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("credit card PIN :");

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("desired ammount  :");

        kreditnaKarticaID.setBackground(new java.awt.Color(204, 204, 204));
        kreditnaKarticaID.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        kreditnaKarticaID.setForeground(new java.awt.Color(0, 0, 0));
        kreditnaKarticaID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kreditnaKarticaID.setText("Input your credit card id here :");
        kreditnaKarticaID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kreditnaKarticaID.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        kreditnaKarticaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreditnaKarticaIDActionPerformed(evt);
            }
        });
        kreditnaKarticaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kreditnaKarticaIDKeyTyped(evt);
            }
        });

        kreditnaKarticaPIN.setBackground(new java.awt.Color(204, 204, 204));
        kreditnaKarticaPIN.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        kreditnaKarticaPIN.setForeground(new java.awt.Color(0, 0, 0));
        kreditnaKarticaPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kreditnaKarticaPIN.setText("input your credit card pin :");
        kreditnaKarticaPIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kreditnaKarticaPIN.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        kreditnaKarticaPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreditnaKarticaPINActionPerformed(evt);
            }
        });
        kreditnaKarticaPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kreditnaKarticaPINKeyTyped(evt);
            }
        });

        KreditnaKarticaKolicinaNovca.setBackground(new java.awt.Color(153, 153, 153));
        KreditnaKarticaKolicinaNovca.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        KreditnaKarticaKolicinaNovca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KreditnaKarticaKolicinaNovca.setText("KolicinaNovca");

        button_potvrdiUplatu_KK.setBackground(new java.awt.Color(153, 153, 153));
        button_potvrdiUplatu_KK.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        button_potvrdiUplatu_KK.setForeground(new java.awt.Color(153, 0, 153));
        button_potvrdiUplatu_KK.setText("confirm");
        button_potvrdiUplatu_KK.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        button_potvrdiUplatu_KK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_potvrdiUplatu_KKActionPerformed(evt);
            }
        });

        button_nazad_KK.setBackground(new java.awt.Color(153, 153, 153));
        button_nazad_KK.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        button_nazad_KK.setForeground(new java.awt.Color(153, 0, 153));
        button_nazad_KK.setText("back");
        button_nazad_KK.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        button_nazad_KK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nazad_KKActionPerformed(evt);
            }
        });

        izabranoGorivo_kk.setForeground(new java.awt.Color(153, 0, 153));
        izabranoGorivo_kk.setText("izabranoGorivo_kk");

        kolicinaGoriva_kk.setForeground(new java.awt.Color(153, 0, 153));
        kolicinaGoriva_kk.setText("kolicinaGoriva_kk");

        ukupnoUplaceno_kk.setForeground(new java.awt.Color(153, 0, 153));
        ukupnoUplaceno_kk.setText("ukupnoUplaceno_kk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kreditnaKarticaID, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(kreditnaKarticaPIN)
                    .addComponent(KreditnaKarticaKolicinaNovca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(button_potvrdiUplatu_KK, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(button_nazad_KK, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(izabranoGorivo_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(kolicinaGoriva_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(ukupnoUplaceno_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kreditnaKarticaID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kreditnaKarticaPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KreditnaKarticaKolicinaNovca, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_potvrdiUplatu_KK, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_nazad_KK, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izabranoGorivo_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolicinaGoriva_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ukupnoUplaceno_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kreditnaKarticaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreditnaKarticaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreditnaKarticaIDActionPerformed

    private void kreditnaKarticaIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kreditnaKarticaIDKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_kreditnaKarticaIDKeyTyped

    private void kreditnaKarticaPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreditnaKarticaPINActionPerformed

    }//GEN-LAST:event_kreditnaKarticaPINActionPerformed

    private void kreditnaKarticaPINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kreditnaKarticaPINKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_kreditnaKarticaPINKeyTyped

    private void button_potvrdiUplatu_KKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_potvrdiUplatu_KKActionPerformed

        int CreditCardID = Integer.parseInt(kreditnaKarticaID.getText());
        int CreditCardPIN = Integer.parseInt(kreditnaKarticaPIN.getText());

        int kreditnaKarticaKolicinaNovca = Integer.parseInt(KreditnaKarticaKolicinaNovca.getText());
        double KolicinaGoriva = Double.parseDouble(kolicinaGoriva_kk.getText());
        String KojeGorivo = izabranoGorivo_kk.getText();

        int Uplaceno_kk = (kreditnaKarticaKolicinaNovca);
        final int kusur = 0;

        if((CreditCardID==creditCardID1) && (CreditCardPIN==creditCardPin1)){
            System.out.println("Obrada u toku;");
            if(kreditnaKarticaKolicinaNovca<=creditCardBalance1){

                System.out.println("Transakcija uspjesna. " + "Molimo sacekajte vas racun. ");

                String msg2 = String.valueOf(Uplaceno_kk);
                String msg1 = String.valueOf(kreditnaKarticaKolicinaNovca);
                String msg3 = String.valueOf(kusur);
                String msg4 = String.valueOf(KolicinaGoriva);
                String msg5 = String.valueOf(KojeGorivo);

                new Racun(msg2,msg1,msg3,msg4,msg5).setVisible(true);

                close();

            }

            else
            System.out.println("Nemate dovoljno sredstava na racunu.");
        }

        else if((CreditCardID==creditCardID2) && (CreditCardPIN==creditCardPin2)){
            System.out.println("Obrada u toku;");
            if(kreditnaKarticaKolicinaNovca<=creditCardBalance2){

                System.out.println("Transakcija uspjesna. " + "Molimo sacekajte vas racun. ");

                String msg2 = String.valueOf(Uplaceno_kk);
                String msg1 = String.valueOf(kreditnaKarticaKolicinaNovca);
                String msg3 = String.valueOf(kusur);
                String msg4 = String.valueOf(KolicinaGoriva);
                String msg5 = String.valueOf(KojeGorivo);

                new Racun(msg2,msg1,msg3,msg4,msg5).setVisible(true);

                close();

            }

            else
            System.out.println("Nemate dovoljno sredstava na racunu.");
        }

        else if((CreditCardID==creditCardID3) && (CreditCardPIN==creditCardPin3)){
            System.out.println("Obrada u toku;");

            if(kreditnaKarticaKolicinaNovca<=creditCardBalance3){

                System.out.println("Transakcija uspjesna. " + "Molimo sacekajte vas racun. ");

                String msg2 = String.valueOf(Uplaceno_kk);
                String msg1 = String.valueOf(kreditnaKarticaKolicinaNovca);
                String msg3 = String.valueOf(kusur);
                String msg4 = String.valueOf(KolicinaGoriva);
                String msg5 = String.valueOf(KojeGorivo);

                //String msg3 = String.valueOf(rand);
                new Racun(msg2,msg1,msg3,msg4,msg5).setVisible(true);

                close();
                //new Racun().setVisible(true);

            }

            else
            System.out.println("Nemate dovoljno sredstava na racunu.");
        }

        else
        System.out.println("Uneseni podatci nisu tacni.");
    }//GEN-LAST:event_button_potvrdiUplatu_KKActionPerformed

    private void button_nazad_KKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nazad_KKActionPerformed
        close();
        PaymentSelection ps = new PaymentSelection();
        ps.setVisible(true);
    }//GEN-LAST:event_button_nazad_KKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreditnaKartica_placanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreditnaKartica_placanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreditnaKartica_placanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreditnaKartica_placanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreditnaKartica_placanje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KreditnaKarticaKolicinaNovca;
    private javax.swing.JButton button_nazad_KK;
    private javax.swing.JButton button_potvrdiUplatu_KK;
    private javax.swing.JLabel izabranoGorivo_kk;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kolicinaGoriva_kk;
    private javax.swing.JTextField kreditnaKarticaID;
    private javax.swing.JTextField kreditnaKarticaPIN;
    private javax.swing.JLabel ukupnoUplaceno_kk;
    // End of variables declaration//GEN-END:variables
}
