/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selfservicestation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PaymentSelection extends javax.swing.JFrame {

    /**
     * Creates new form PaymentSelection
     */
    public PaymentSelection() {
        initComponents();
    }
    
    public PaymentSelection (String TipGoriva){
        initComponents();
      
        tip_goriva.setText(TipGoriva);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tip_goriva = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_novac = new javax.swing.JButton();
        button_kreditna_kartica = new javax.swing.JButton();
        button_karticaOd_pumpe1 = new javax.swing.JButton();
        button_nazad = new javax.swing.JButton();
        kolicinaNovca_ps = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Private\\Eclipse workspace\\SelfServiceStation\\images\\SSGSS_naslovna.jpg")); // NOI18N

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Select you payment type");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(481, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        tip_goriva.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        tip_goriva.setForeground(new java.awt.Color(255, 255, 255));
        tip_goriva.setText("Fuel type");

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Payment type and ammount of money");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        button_novac.setBackground(new java.awt.Color(255, 255, 255));
        button_novac.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        button_novac.setForeground(new java.awt.Color(153, 0, 153));
        button_novac.setText("Cash");
        button_novac.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        button_novac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_novacActionPerformed(evt);
            }
        });

        button_kreditna_kartica.setBackground(new java.awt.Color(255, 255, 255));
        button_kreditna_kartica.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        button_kreditna_kartica.setForeground(new java.awt.Color(153, 0, 153));
        button_kreditna_kartica.setText("credit card");
        button_kreditna_kartica.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        button_kreditna_kartica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kreditna_karticaActionPerformed(evt);
            }
        });

        button_karticaOd_pumpe1.setBackground(new java.awt.Color(255, 255, 255));
        button_karticaOd_pumpe1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        button_karticaOd_pumpe1.setForeground(new java.awt.Color(153, 0, 153));
        button_karticaOd_pumpe1.setText("gas station card");
        button_karticaOd_pumpe1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        button_karticaOd_pumpe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_karticaOd_pumpe1ActionPerformed(evt);
            }
        });

        button_nazad.setBackground(new java.awt.Color(255, 255, 255));
        button_nazad.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        button_nazad.setForeground(new java.awt.Color(153, 0, 153));
        button_nazad.setText("back");
        button_nazad.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        button_nazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nazadActionPerformed(evt);
            }
        });

        kolicinaNovca_ps.setBackground(new java.awt.Color(255, 255, 255));
        kolicinaNovca_ps.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        kolicinaNovca_ps.setForeground(new java.awt.Color(0, 0, 0));
        kolicinaNovca_ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kolicinaNovca_ps.setText("ammount of money :");
        kolicinaNovca_ps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolicinaNovca_psKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tip_goriva)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button_novac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(button_kreditna_kartica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(button_karticaOd_pumpe1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(kolicinaNovca_ps, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(button_nazad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tip_goriva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(kolicinaNovca_ps, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_novac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_kreditna_kartica, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_karticaOd_pumpe1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_nazad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private final double Plin_cijena = 1.05;
    private final double Benzin_cijena = 2.10;
    private final double Dizel_cijena = 2.22;
    
    private final double PlinPopust_cijena = 1.00;
    private final double BenzinPopust_cijena = 2.05;
    private final double DizelPopust_cijena = 2.17;
    
    private void button_novacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_novacActionPerformed

        String KojeGorivo = tip_goriva.getText();
        int KolicinaNovca = Integer.parseInt(kolicinaNovca_ps.getText());

        double KolicinaGoriva_Plin=(KolicinaNovca/Plin_cijena);
        KolicinaGoriva_Plin =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGoriva_Plin));

        double KolicinaGoriva_Benzin=(KolicinaNovca/Benzin_cijena);
        KolicinaGoriva_Benzin =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGoriva_Benzin));

        double KolicinaGoriva_Dizel=(KolicinaNovca/Dizel_cijena);
        KolicinaGoriva_Dizel =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGoriva_Dizel));

        try{

            if (KolicinaNovca>=5 && KojeGorivo.equals("Gas")) {

                String message1 = String.valueOf(KolicinaNovca);
                String message2 = String.valueOf(KolicinaGoriva_Plin);
                String message3 = String.valueOf(KojeGorivo);
                close();
                new Novac_placanje(message1, message2,message3).setVisible(true);
            }
            else if (KolicinaNovca>=5 && KojeGorivo.equals("Petrol")) {

                String message1 = String.valueOf(KolicinaNovca);
                String message2 = String.valueOf(KolicinaGoriva_Benzin);
                String message3 = String.valueOf(KojeGorivo);
                close();
                new Novac_placanje(message1, message2, message3).setVisible(true);
            }
            else if (KolicinaNovca>=5 && KojeGorivo.equals("Diesel")) {

                String message1 = String.valueOf(KolicinaNovca);
                String message2 = String.valueOf(KolicinaGoriva_Dizel);
                String message3 = String.valueOf(KojeGorivo);
                close();
                new Novac_placanje(message1, message2, message3).setVisible(true);
            }

            //OVAJ DIO TREBA ODRADITI... NOVI JFRAME KOJI INTERCEPTUJE I VRACA ISTI JFRAME..............
            //
            //
            else if (KolicinaNovca<5){
                JOptionPane.showMessageDialog(null,"Unjeli ste nedovoljnu kolicinu! Minimalna kolicina je 5KM. Sistem se restartuje.... ", null, JOptionPane.ERROR_MESSAGE);

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"unesena pogresna bla bla", null, JOptionPane.ERROR_MESSAGE);

        }

        

    }//GEN-LAST:event_button_novacActionPerformed

    private void button_kreditna_karticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kreditna_karticaActionPerformed

        String KojeGorivo = tip_goriva.getText();
        int KolicinaNovca = Integer.parseInt(kolicinaNovca_ps.getText());

        double KolicinaGoriva_Plin=(KolicinaNovca/Plin_cijena);
        KolicinaGoriva_Plin =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGoriva_Plin));

        double KolicinaGoriva_Benzin=(KolicinaNovca/Benzin_cijena);
        KolicinaGoriva_Benzin =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGoriva_Benzin));

        double KolicinaGoriva_Dizel=(KolicinaNovca/Dizel_cijena);
        KolicinaGoriva_Dizel =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGoriva_Dizel));

        try{

            if (KolicinaNovca>=5 && KojeGorivo.equals("Gas")) {

                String message1 = String.valueOf(KojeGorivo);
                String message2 = String.valueOf(KolicinaNovca);
                String message3 = String.valueOf(KolicinaGoriva_Plin);

                close();
                new KreditnaKartica_placanje(message1, message2, message3).setVisible(true);
            }
            else if (KolicinaNovca>=5 && KojeGorivo.equals("Petrol")) {

                String message1 = String.valueOf(KojeGorivo);
                String message2 = String.valueOf(KolicinaNovca);
                String message3 = String.valueOf(KolicinaGoriva_Benzin);

                close();
                new KreditnaKartica_placanje(message1, message2, message3).setVisible(true);
            }
            else if (KolicinaNovca>=5 && KojeGorivo.equals("Diesel")) {

                String message1 = String.valueOf(KojeGorivo);
                String message2 = String.valueOf(KolicinaNovca);
                String message3 = String.valueOf(KolicinaGoriva_Dizel);

                close();
                new KreditnaKartica_placanje(message1, message2, message3).setVisible(true);
            }
            else if (KolicinaNovca<5){
                JOptionPane.showMessageDialog(null,"Unjeli ste nedovoljnu kolicinu! Minimalna kolicina je 5KM. Sistem se restartuje.... ", null, JOptionPane.ERROR_MESSAGE);

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"unesena pogresna bla bla", null, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_button_kreditna_karticaActionPerformed

    private void button_karticaOd_pumpe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_karticaOd_pumpe1ActionPerformed

        String KojeGorivo = tip_goriva.getText();
        int KolicinaNovca = Integer.parseInt(kolicinaNovca_ps.getText());

        double KolicinaGorivaPopust_Plin=(KolicinaNovca/PlinPopust_cijena);
        KolicinaGorivaPopust_Plin =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGorivaPopust_Plin));

        double KolicinaGorivaPopust_Benzin=(KolicinaNovca/BenzinPopust_cijena);
        KolicinaGorivaPopust_Benzin =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGorivaPopust_Benzin));

        double KolicinaGorivaPopust_Dizel=(KolicinaNovca/DizelPopust_cijena);
        KolicinaGorivaPopust_Dizel =Double.parseDouble(new DecimalFormat("##.####").format(KolicinaGorivaPopust_Dizel));

        try{

            if (KolicinaNovca>=5 && KojeGorivo.equals("Gas")) {

                String message1 = String.valueOf(KojeGorivo);
                String message2 = String.valueOf(KolicinaNovca);
                String message3 = String.valueOf(KolicinaGorivaPopust_Plin);

                close();
                new KarticaPumpa_placanje(message1, message2, message3).setVisible(true);
            }
            else if (KolicinaNovca>=5 && KojeGorivo.equals("Petrol")) {

                String message1 = String.valueOf(KojeGorivo);
                String message2 = String.valueOf(KolicinaNovca);
                String message3 = String.valueOf(KolicinaGorivaPopust_Benzin);

                close();
                new KarticaPumpa_placanje(message1, message2, message3).setVisible(true);
            }
            else if (KolicinaNovca>=5 && KojeGorivo.equals("Diesel")) {

                String message1 = String.valueOf(KojeGorivo);
                String message2 = String.valueOf(KolicinaNovca);
                String message3 = String.valueOf(KolicinaGorivaPopust_Dizel);

                close();
                new KarticaPumpa_placanje(message1, message2, message3).setVisible(true);
            }
            else if (KolicinaNovca<5){
                JOptionPane.showMessageDialog(null,"Unjeli ste nedovoljnu kolicinu! Minimalna kolicina je 5KM. Sistem se restartuje.... ", null, JOptionPane.ERROR_MESSAGE);

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"unesena pogresna bla bla", null, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_button_karticaOd_pumpe1ActionPerformed

    private void button_nazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nazadActionPerformed
        close();
        FuelType ft = new FuelType();
        ft.setVisible(true);
    }//GEN-LAST:event_button_nazadActionPerformed

    private void kolicinaNovca_psKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolicinaNovca_psKeyTyped

        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_kolicinaNovca_psKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_karticaOd_pumpe1;
    private javax.swing.JButton button_kreditna_kartica;
    private javax.swing.JButton button_nazad;
    private javax.swing.JButton button_novac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kolicinaNovca_ps;
    private javax.swing.JLabel tip_goriva;
    // End of variables declaration//GEN-END:variables
}
