/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selfservicestation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author PC
 */
public class Racun extends javax.swing.JFrame {

   

    /**
     * Creates new form Racun
     */
    public Racun() {
        initComponents();
    }

     public Racun (String IznosUplate, String UkupnaSuma, String Kusur, String KolicinaGoriva, String KojeGorivo){
        initComponents();
      
        ukupnoUplaceno_Racun.setText(IznosUplate);
        iznosUplate_Racun.setText(UkupnaSuma);
        kusur_novac.setText(Kusur);
        kolicinGoriva_Racun.setText(KolicinaGoriva);
        izabranoGorivo.setText(KojeGorivo);
        
        
    }
    
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        brojRacuna_Racun = new javax.swing.JLabel();
        izabranoGorivo = new javax.swing.JLabel();
        kolicinGoriva_Racun = new javax.swing.JLabel();
        iznosUplate_Racun = new javax.swing.JLabel();
        ukupnoUplaceno_Racun = new javax.swing.JLabel();
        kusur_novac = new javax.swing.JLabel();
        printajRacun_novac = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("                          RECIEP");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("reciep ID :");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("fuel selected :");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("fuel ammount :");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("desired ammount :");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("total payment : ");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("change :");

        brojRacuna_Racun.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        brojRacuna_Racun.setForeground(new java.awt.Color(255, 255, 255));
        brojRacuna_Racun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brojRacuna_Racun.setText("Broj racuna : ");

        izabranoGorivo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        izabranoGorivo.setForeground(new java.awt.Color(0, 0, 0));
        izabranoGorivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        izabranoGorivo.setText("Broj racuna : ");

        kolicinGoriva_Racun.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        kolicinGoriva_Racun.setForeground(new java.awt.Color(0, 0, 0));
        kolicinGoriva_Racun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kolicinGoriva_Racun.setText("Broj racuna : ");

        iznosUplate_Racun.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        iznosUplate_Racun.setForeground(new java.awt.Color(0, 0, 0));
        iznosUplate_Racun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iznosUplate_Racun.setText("Broj racuna : ");

        ukupnoUplaceno_Racun.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        ukupnoUplaceno_Racun.setForeground(new java.awt.Color(0, 0, 0));
        ukupnoUplaceno_Racun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ukupnoUplaceno_Racun.setText("Broj racuna : ");

        kusur_novac.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        kusur_novac.setForeground(new java.awt.Color(0, 0, 0));
        kusur_novac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kusur_novac.setText("Broj racuna : ");

        printajRacun_novac.setBackground(new java.awt.Color(255, 255, 255));
        printajRacun_novac.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        printajRacun_novac.setForeground(new java.awt.Color(153, 0, 153));
        printajRacun_novac.setText("print reciepe");
        printajRacun_novac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printajRacun_novacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kusur_novac, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brojRacuna_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izabranoGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kolicinGoriva_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iznosUplate_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ukupnoUplaceno_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(printajRacun_novac, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brojRacuna_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izabranoGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolicinGoriva_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iznosUplate_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ukupnoUplaceno_Racun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kusur_novac, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(printajRacun_novac, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
     
    
   
    private void printajRacun_novacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printajRacun_novacActionPerformed
        
     int min = 100000;
     int max = 400000;
     int brojRacuna = (int)Math.floor(Math.random()*(max-min+1)+min);
       
       
       
       
        int cashPayment = Integer.parseInt(iznosUplate_Racun.getText());
        int kolicinaNovca = Integer.parseInt(ukupnoUplaceno_Racun.getText());
        double KolicinaGoriva = Double.parseDouble(kolicinGoriva_Racun.getText());
        String KojeGorivo = izabranoGorivo.getText();
        double Kusur = Double.parseDouble(kusur_novac.getText());
        int BrojRacuna = brojRacuna;
        
        
        
        
                    String msg2 = String.valueOf(kolicinaNovca);
                    String msg1 = String.valueOf(cashPayment);
                    String msg3 = String.valueOf(Kusur);
                    String msg4 = String.valueOf(KolicinaGoriva);
                    String msg5 = String.valueOf(KojeGorivo);
                    String msg6 = String.valueOf(BrojRacuna);
                    
        
        
       /* System.out.println("**** Fiskalni racun za transakciju ****");
        System.out.println("**** Broj racuna je : "  + brojRacuna + " ****" + "\n"
            +"**** Tip goriva je : " +izabranoGorivo.getText()+ " ****");
        System.out.println("**** Fuel ammount is : "+ kolicinGoriva_Racun.getText() +" ****");
        System.out.println("**** Desired ammount is : "+ iznosUplate_Racun.getText() +" ****");
        System.out.println("**** Total payment is : "+ ukupnoUplaceno_Racun.getText() +" ****");
        System.out.println("**** Change is : "+ kusur_novac.getText() +" ****");
        */

        
        
        close();
        new IsprintaniRacun(msg2, msg1, msg3, msg4, msg5, msg6).setVisible(true);
        new Zavrsna().setVisible(true);

    }//GEN-LAST:event_printajRacun_novacActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Racun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brojRacuna_Racun;
    private javax.swing.JLabel izabranoGorivo;
    private javax.swing.JLabel iznosUplate_Racun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kolicinGoriva_Racun;
    private javax.swing.JLabel kusur_novac;
    private javax.swing.JButton printajRacun_novac;
    private javax.swing.JLabel ukupnoUplaceno_Racun;
    // End of variables declaration//GEN-END:variables
}
